//
//  FirstViewControllerRouter.swift
//  JsonPar
//
//  Created by Amruta on 20/06/19.
//  Copyright (c) 2019 Bhargavi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
// MARK: Navigation Protocol

@objc protocol FirstViewControllerRoutingLogic
{
  func routeToSender(segue: UIStoryboardSegue?)
}
// MARK: DataPassing Protocol

protocol FirstViewControllerDataPassing
{
  var dataStore: FirstViewControllerDataStore? { get }
}

class FirstViewControllerRouter: NSObject, FirstViewControllerRoutingLogic, FirstViewControllerDataPassing
{
  
  weak var viewController: FirstViewControllerViewController?
  var dataStore: FirstViewControllerDataStore?
  
  // MARK: Routing
  
  func routeToSender(segue: UIStoryboardSegue?)
  {
  
   let storyboard = UIStoryboard(name: "Main", bundle: nil)
   let destinationVC = storyboard.instantiateViewController(withIdentifier: "SecondViewControllerViewController") as! SecondViewControllerViewController
   var destinationDS = destinationVC.router!.dataStore!
     passDataToReceiver(source: dataStore!, destination: &destinationDS)
   navigateToSender(source: viewController!, destination: destinationVC)
   }


  // MARK: Navigation
  
  func navigateToSender(source: FirstViewControllerViewController, destination: SecondViewControllerViewController)
  {
  source.show(destination, sender: nil)
}
  
  // MARK: Passing data
  
  func passDataToReceiver(source: FirstViewControllerDataStore, destination: inout SecondViewControllerDataStore)
  {
    
    destination.name = source.name
  }
}
