//
//  SecondViewControllerModels.swift
//  JsonPar
//
//  Created by Amruta on 20/06/19.
//  Copyright (c) 2019 Bhargavi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SecondViewController
{
  // MARK: Use cases
  
  enum Sender
  {
    struct Request
    {
    }
    struct Response
    {
         let title: String
    }
    struct ViewModel
    {
        let title: String
    }
  }
    
    enum TellReceiver
    {
        struct Request
        {
             let title: String
        }
        struct Response
        {
        }
        struct ViewModel
        {
           
        }
    }
}
