//
//  SecondViewControllerInteractor.swift
//  JsonPar
//
//  Created by Amruta on 20/06/19.
//  Copyright (c) 2019 Bhargavi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
// MARK: BusinessLogic Protocol

protocol SecondViewControllerBusinessLogic
{
  func doSomething(request: SecondViewController.Sender.Request)
     func tellReceiver(request: SecondViewController.TellReceiver.Request)
}

protocol SecondViewControllerDataStore
{
  var name: String { get set }
}

class SecondViewControllerInteractor: SecondViewControllerBusinessLogic, SecondViewControllerDataStore
{
    var presenter: SecondViewControllerPresentationLogic?
    var worker: SecondViewControllerWorker?
    var name: String = ""
    
  
  // MARK: Do something
  
  func doSomething(request: SecondViewController.Sender.Request)
  {
    worker=SecondViewControllerWorker()
    worker?.doSomeWork()
    let response = SecondViewController.Sender.Response(title:name)
    presenter?.presentSomething(response: response)
  }
    // MARK: Tell Receiver
    
    func tellReceiver(request: SecondViewController.TellReceiver.Request) {
      
        name=request.title
        let response = SecondViewController.TellReceiver.Response()
        presenter?.presentTellReceiver(response: response)
    }
    
    
}
