//
//  SecondViewControllerPresenter.swift
//  JsonPar
//
//  Created by Amruta on 20/06/19.
//  Copyright (c) 2019 Bhargavi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondViewControllerPresentationLogic
{
  func presentSomething(response: SecondViewController.Sender.Response)
    func presentTellReceiver(response:SecondViewController.TellReceiver.Response)
}

class SecondViewControllerPresenter: SecondViewControllerPresentationLogic
{
  weak var viewController: SecondViewControllerDisplayLogic?
  
  // MARK: Present Something
  
  func presentSomething(response: SecondViewController.Sender.Response)
  {
    let appInfo=response.title
    let viewModel = SecondViewController.Sender.ViewModel(title: appInfo)
    viewController?.displaySomething(viewModel: viewModel)
  }
    func presentTellReceiver(response: SecondViewController.TellReceiver.Response)
    {
        let viewModel = SecondViewController.TellReceiver.ViewModel()
        viewController?.displayTellReceiver(viewModel: viewModel)
    }
}
